/** 界面文案集中管理，为后续中英切换留入口（MVP 只上中文）。 */
export const strings = {
  appName: 'PinAtlas',
  tagline: '芯片引脚数据库与可视化查询',
  searchPlaceholder: '搜索型号，如 STM32F103C8 / F103 / LQFP48',
  searchShortcut: '⌘K',
  searchHint: '↑↓ 选择 · Enter 打开 · Esc 清空；多个关键词用空格分隔（如 F103 LQFP48），也支持订货号（C8T6 / VGT6）',
  expandAll: '展开其余',
  families: '系列',
  chips: '型号',
  packages: '封装',
  noResult: '没有匹配的型号',
  noResultHint: '数据集只覆盖已收录型号，可在 pinatlas-data 仓库查看收录范围。',
  selectChip: '从左侧选择一个型号',
  selectPin: '点击引脚查看复用功能',
  selectPinHint: '在左侧引脚图上点任意一个引脚',
  loading: '加载中…',
  pinSearchPlaceholder: '搜引脚：PB9 / 96 / CAN1_TX',
  pinSearchHit: '命中',
  pinSearchNav: '↑↓ 切换命中引脚',
  pinSearchNone: '没有匹配的引脚',
  loadFailed: '数据加载失败',
  retry: '重试',
  pinNumber: '引脚号',
  padName: '引脚名',
  type: '类型',
  functions: '复用功能',
  afColumn: 'AF',
  variantLabel: '变体',
  baseVariant: '基础定义',
  variantNone: '该变体下未连接',
  afUnknown: '该系列上游没有 AF 号数据，AF 列显示 “-”',
  afExtiNone: 'EXTI 线没有交替功能号（AF），触发/屏蔽由 EXTI 寄存器配置',
  systemGroup: '系统 / 时钟',
  extiHint: '可作为该线的外部中断源（EXTI 线号 = 引脚序号，具体触发/屏蔽由 EXTI 寄存器配置）',
  memory: '存储',
  flash: 'Flash',
  ram: 'RAM',
  ioCount: 'IO 数',
  parts: '订货号',
  dataSource: '数据来源',
  dataVersion: '数据版本',
  disclaimer: '示意排布，非按比例；引脚序号按俯视逆时针排列。',
  gridViewNote: 'BGA/WLCSP 按底视（看球面）排布。',
  layoutWarning: '布局提示',
  sameDie: '同 die 其他封装',
  noChipSelected: '未选择型号',
  pins: '引脚',
  exampleHint: '试试 STM32F103C8Tx（LQFP48）或 STM32G031K8Tx（LQFP32，含引脚重映射）',
}

export type Strings = typeof strings
