/** 界面文案集中管理，为后续中英切换留入口（MVP 只上中文）。 */
export const strings = {
  appName: 'PinAtlas',
  tagline: '芯片引脚数据库与可视化查询',
  searchPlaceholder: '搜索型号，如 STM32F103C8 / F103 / LQFP48',
  searchShortcut: '⌘K',
  families: '系列',
  chips: '型号',
  packages: '封装',
  noResult: '没有匹配的型号',
  noResultHint: '数据集只覆盖已收录型号，可在 pinatlas-data 仓库查看收录范围。',
  selectChip: '从左侧选择一个型号',
  selectPin: '点击引脚查看复用功能',
  loading: '加载中…',
  loadFailed: '数据加载失败',
  retry: '重试',
  pinNumber: '引脚号',
  padName: '引脚名',
  type: '类型',
  functions: '复用功能',
  afColumn: 'AF',
  variantLabel: '变体',
  baseVariant: '基础定义',
  variantNone: '该变体下未连接',
  afUnknown: '该系列上游没有 AF 号数据，AF 列显示 “-”',
  systemGroup: '系统 / 时钟',
  memory: '存储',
  flash: 'Flash',
  ram: 'RAM',
  ioCount: 'IO 数',
  parts: '订货号',
  dataSource: '数据来源',
  dataVersion: '数据版本',
  disclaimer: '示意排布，非按比例；引脚序号按俯视逆时针排列。',
  gridViewNote: 'BGA/WLCSP 按底视（看球面）排布。',
  layoutWarning: '布局提示',
  sameDie: '同 die 其他封装',
  noChipSelected: '未选择型号',
  pins: '引脚',
  exampleHint: '试试 STM32F103C8Tx（LQFP48）或 STM32G031K8Tx（LQFP32，含引脚重映射）',
}

export type Strings = typeof strings
